module android.R {
    export const id = {
        "content": "content",
        "background": "background",
        "secondaryProgress": "secondaryProgress",
        "progress": "progress",
        "contentPanel": "contentPanel",
        "topPanel": "topPanel",
        "buttonPanel": "buttonPanel",
        "customPanel": "customPanel",
        "custom": "custom",
        "titleDivider": "titleDivider",
        "titleDividerTop": "titleDividerTop",
        "title_template": "title_template",
        "icon": "icon",
        "alertTitle": "alertTitle",
        "scrollView": "scrollView",
        "message": "message",
        "button1": "button1",
        "button2": "button2",
        "button3": "button3",
        "leftSpacer": "leftSpacer",
        "rightSpacer": "rightSpacer",
        "text1": "text1",
        "action_bar_center_layout": "action_bar_center_layout",
        "action_bar_title": "action_bar_title",
        "action_bar_sub_title": "action_bar_sub_title",
        "action_bar_left": "action_bar_left",
        "action_bar_right": "action_bar_right",
        "parentPanel": "parentPanel",
        "progress_percent": "progress_percent",
        "progress_number": "progress_number",
        "title": "title",
        "shortcut": "shortcut",
        "select_dialog_listview": "select_dialog_listview"
};
}